class StudyLoopError(Exception):
    """Base error. CLI catches this, prints args[0] + suggested action, exits 1."""


class CourseNotFound(StudyLoopError): ...
class InvalidWorkspace(StudyLoopError): ...
class InvalidSchema(StudyLoopError): ...
class DuplicateEvent(StudyLoopError): ...
class UnknownQuestion(StudyLoopError): ...
class UnknownKC(StudyLoopError): ...
class StateLockTimeout(StudyLoopError): ...
class ValidationFailed(StudyLoopError): ...
